version: '3.9'
services:
  pgdatabase:
    image: pgvector/pgvector:0.7.4-pg16
    environment:
      - POSTGRES_USER=${PGVECTOR_USER:-postgres}
      - POSTGRES_PASSWORD=${PGVECTOR_PASSWORD:-postgres}
      - POSTGRES_DB=${PGVECTOR_DATABASE:-brevia}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PGVECTOR_PORT:-5432}:5432
  pgadmin:
    image: dpage/pgadmin4
    profiles: ["admin"]
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-4000}:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
    name: ${PGVECTOR_VOLUME_NAME:-pgdata}
  pgadmindata:
    name: ${PGADMIN_VOLUME_NAME:-pgadmindata}
